name: dienos_calendar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ./domain
  data:
    path: ./data
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  table_calendar: ^3.1.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.4
  fl_chart: ^0.70.2
  speech_to_text: ^7.3.0
  home_widget: ^0.9.0
  file_picker: ^8.1.7
  fluttertoast: ^8.2.12
  archive: ^3.6.1
  device_info_plus: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
